-- ════════════════════════════════════════════════════════════════════════
--  smutHub · finalized Notion glossary sync
--
--  Syncs the reviewed 559-row Beginner Romantasy Glossary into 557 unique
--  canonical terms (two shorthand aliases resolve to their canonical records).
--
--  Idempotent: rerunning updates the canonical definition and publication
--  flags for the same (category, slug) without creating duplicates.
-- ════════════════════════════════════════════════════════════════════════

insert into tags (
  category,
  slug,
  label,
  description,
  has_page,
  glossary_visible
) values
('culture','ao3','AO3','Archive of Our Own',true,true),
('culture','arc','ARC','Advance Reader Copy — a free pre-publication copy given to reviewers, BookTokers, and bookstagrammers in exchange for an honest review.',true,true),
('culture','book-boyfriend','Book Boyfriend','A fictional hero you''re emotionally attached to.',true,true),
('culture','book-hangover','Book Hangover','The inability to start a new book because you''re still emotionally compromised by the last one.',true,true),
('culture','booktok','BookTok','The romance and romantasy corner of TikTok — primary recommendation engine and discovery surface for the genre since \~2020.',true,true),
('culture','christmas','Christmas / Holiday','Set during or centered around Christmas — seasonal romance, cocoa, snowed-in adjacency.',true,true),
('culture','cliffhanger','Cliffhanger','The story ends with major unresolved events. Use to set expectations — many readers want to know before they start.',true,true),
('culture','content-warnings-cw','Content Warnings (CW)','alerts about potentially triggering content. usually at the front of the book or in the blurb. Use these.',true,true),
('culture','dnf','DNF','Did Not Finish — a book you stopped reading. No judgment; not every book is for every reader.',true,true),
('culture','ff','FF','A female / female pairing.',true,true),
('culture','fmc','FMC','Female Main Character — the heroine.',true,true),
('culture','frontlist','Frontlist','a publishers new releases. The fresh & new stuff',true,true),
('culture','good-girl','Good Girl','Praise used in intimate contexts. The two-word phrase doing the most heavy lifting in modern romance.',true,true),
('culture','grey-sweatpants','Grey Sweatpants','A piece of clothing with disproportionate cultural significance in romance reader spaces.',true,true),
('culture','hea','HEA','Happily Ever After — the couple ends up together and committed. The genre''s baseline promise.',true,true),
('culture','hfn','HFN','Happily For Now — the couple is together and happy, but the future isn''t fully defined. Still a positive ending.',true,true),
('culture','hopeful-ending','Hopeful Ending','An ending that leaves characters in a positive or optimistic position — not strictly HEA, but readers can breathe.',true,true),
('culture','hr','HR','historical romance',true,true),
('culture','indie-author','Indie Author','Self-published authors — increasingly the engine of romance''s output and innovation, especially in romantasy and dark romance.',true,true),
('culture','kindle-unlimited','Kindle Unlimited (KU)','Amazon''s ebook subscription service. Many indie romance authors are KU-exclusive, which is why a lot of the genre lives there.',true,true),
('culture','li','LI','Love Interest — the romantic counterpart to the main character.',true,true),
('culture','mce','Main Character Energy','When a character commands their own story — presence, agency, the protagonism reader-immersion runs on.',true,true),
('culture','mc-romance','MC romance','motorcycle club romance. bikers, leather, loyalty',true,true),
('culture','mf','MF','A male / female pairing.',true,true),
('culture','mfm','MFM','A pairing of two men and one woman where the men are involved with the woman but NOT each other.',true,true),
('culture','mm','MM','A male / male pairing.',true,true),
('culture','mmc','MMC','Male Main Character — the hero, often the love interest in MF romance.',true,true),
('culture','mmf','MMF','A pairing of two men and one woman that INCLUDES male/male contact between the men.',true,true),
('culture','na-new-adult','NA (new adult)','romance featuring characters typically 18-25. between YA and adult',true,true),
('culture','no-3rd-act-breakup','No Third-Act Break-up','The main couple does not separate before the ending. Reader request for tropes that DON''T appear — increasingly common ask.',true,true),
('culture','ofy','OFY','Obsessed For You — extreme devotion from a love interest. Distinct from creepy by being mutual and (mostly) wanted.',true,true),
('culture','otp','OTP','One True Pairing — the couple you''re ride-or-die for in a book, series, or fandom.',true,true),
('culture','ott','OTT','Over the Top — used affectionately for heroes who are theatrical in their devotion: grand gestures, possessiveness, obsession (consensual).',true,true),
('culture','ott-over-the-top','OTT (Over the Top)','heroes are extra about their love interest. dramatic gestures, possessiveness, obsession (consensual). not subtle. very fun',true,true),
('culture','paranormal-romance-pnr','Paranormal Romance (PNR)','romance with supernatural elemnts: vampires, shifters, witches, faes, etc.',true,true),
('culture','red-flag-parade','Red Flag Parade','A character who is nothing but red flags. Often said affectionately.',true,true),
('culture','snort-laugh','Snort-Laugh','The unflattering laugh a book surprises out of you. Sign of high quality. Frequently happens in public.',true,true),
('culture','tbr','TBR','To Be Read — your reading list. Never shrinks. Only grows.',true,true),
('culture','trope','Trope','A recurring story element or device. NOT a cliché — tropes are the whole reason we''re here.',true,true),
('culture','uf-urban-fantasy','UF (Urban Fantasy)','Fantasy set in a contemporary, usually urban, setting. Magic in the modern world.',true,true),
('culture','wc','Why Choose','A polyamorous trope where the protagonist doesn''t pick — they get all the love interests.',true,true),
('culture','wip','WIP','Work in Progress — a book the author is currently writing.',true,true),
('culture','ya-young-adult','YA (Young Adult)','romance for teens. cleaner content, protagonists under 18',true,true),
('culture','yearning','Yearning','The painful longing between characters who haven''t come together (or have, and now can''t).',true,true),
('format','audiobook','Audiobook','A recorded performance of a book read by one or more narrators.',true,true),
('format','duet','Duet','A story told across two books, often one POV each, or one continuous arc split in two.',true,true),
('format','first-in-series','First in Series','The opening book in a connected series, introducing the world, characters, or larger story arc.',true,true),
('format','interconnected-series','Interconnected Series','Standalones that share a world or supporting cast but can be read independently. Previous protagonists often cameo.',true,true),
('format','interconnected-standalone','Interconnected Standalone','A complete story that can be read alone but shares a world, setting, or recurring characters with other books.',true,true),
('format','long','Long','books between 400 - 599',true,true),
('format','medium','Medium','books between 250 - 399',true,true),
('format','no-cliffhanger','No Cliffhanger','A book that resolves its central arc rather than leaving readers waiting for the next installment.',true,true),
('format','novella','Novella','books between 1 - 149 pages',true,true),
('format','series','Series','Multiple connected books, either one continuous story or interconnected characters in a shared world.',true,true),
('format','short','Short','books between 150 - 249',true,true),
('format','standalone','Standalone','A complete story in a single book — no cliffhanger, no required reading after it.',true,true),
('format','trilogy','Trilogy','A three-book story arc.',true,true),
('kink','age-play','Age Play','A consensual adult role-play dynamic where participants adopt different ages or caregiving roles. All participants are adults.',true,true),
('kink','anal-sex','Anal Sex','Sexual activity involving anal penetration; its presence may be noted in spice or content information.',true,true),
('kink','bondage','Bondage','Restraint dynamics — physical or implied. A BDSM staple.',true,true),
('kink','breeding','Breeding','Pregnancy or impregnation themes central to the romantic fantasy — common in shifter, omegaverse, and dark romance.',true,true),
('kink','childfree','Childfree','A romance where the central couple does not have or does not want children, often ending without a pregnancy or baby epilogue.',true,true),
('kink','consensual-non-consent','Consensual Non-Consent (CNC)','A consent dynamic where partners agree in advance to scenes that mimic non-consent. Negotiated, scripted, safe-worded.',true,true),
('kink','creative-anatomy','Creative Anatomy','A fantasy or monster-romance tag for non-human bodies or anatomy that differs from ordinary human anatomy.',true,true),
('kink','daddy-kink','Daddy Kink','A consensual dynamic involving nurturing, authority, or caregiver themes between adult partners.',true,true),
('kink','double-anal','Double Anal','A form of double penetration involving two objects, toys, or partners penetrating the anus simultaneously.',true,true),
('kink','double-penetration','Double Penetration','Simultaneous penetration in two places, usually involving three or more participants or toys.',true,true),
('kink','double-vaginal','Double Vaginal','A form of double penetration involving two objects, toys, or partners penetrating the vagina simultaneously.',true,true),
('kink','exhibitionism','Exhibitionism','A character gains excitement from being observed or potentially observed during intimate moments.',true,true),
('kink','fem-dom','Fem-Dom','A relationship dynamic where the female partner is dominant.',true,true),
('kink','fetish','Fetish','A specific object, body part, or scenario plays a central role in attraction or intimacy.',true,true),
('kink','harem','Harem','One character develops romantic relationships with multiple partners simultaneously.',true,true),
('kink','masc-dom','Masc-Dom','A relationship dynamic where the masculine partner is dominant.',true,true),
('kink','menage','Ménage','A romantic relationship involving three people.',true,true),
('kink','older-mature','Older / Mature','A tag indicating one or more central characters are middle-aged or older.',true,true),
('kink','pegging','Pegging','Penetration of a partner with a strap-on, commonly referring to anal penetration.',true,true),
('kink','poly','Polyamory','A consensual romantic relationship involving more than two people — all parties knowing, all consenting.',true,true),
('kink','possessive','Possessive','A character displays strong territorial or protective behavior toward a love interest.',true,true),
('kink','praise','Praise','A dynamic where affirmation and praise are central to intimacy.',true,true),
('kink','primal-chase','Primal / Chase Play','Intimacy incorporating pursuit, hunting, or instinct — predator/prey dynamics.',true,true),
('kink','role-switching','Role Switching','Partners alternate between dominant and submissive roles.',true,true),
('kink','somnophilia','Somnophilia','A negotiated adult kink involving sexual activity while one partner appears asleep or is asleep, requiring explicit advance consent.',true,true),
('kink','spanking','Spanking','Impact play involving spanking — punishment, praise, both.',true,true),
('li-archetype','actor-hero','Actor Hero','A hero working in entertainment or film.',true,true),
('li-archetype','age-old-hero','Age-Old Hero','A supernatural character significantly older than their human partner.',true,true),
('li-archetype','alpha-male','Alpha Male','A confident, dominant, assertive male love interest — the leader, the protector, the one who decides.',true,true),
('li-archetype','bad-boy','Bad Boy','A rebellious or rule-breaking hero — tattoos optional, redemption arc mandatory.',true,true),
('li-archetype','biker','Biker','A hero involved in motorcycle culture — leather, brotherhood, loyalty over law.',true,true),
('li-archetype','bodyguard-hero','Bodyguard / Protector Hero','A hero tasked with protecting others.',true,true),
('li-archetype','ceo','CEO / Tycoon','A business leader or corporate executive — power, money, devastating in a suit.',true,true),
('li-archetype','cowboy','Cowboy','A rancher, horseman, or western hero. Quiet competence, calloused hands.',true,true),
('li-archetype','cruel-hero','Cruel / Bully Hero','A hero who initially mistreats or antagonizes the protagonist — the path from cruelty to devotion.',true,true),
('li-archetype','dominant','Dominant','A love interest who takes the lead — in the relationship and the bedroom.',true,true),
('li-archetype','dominant-mmc','Dominant MMC','A male main character who takes a leading or controlling role in the relationship — bedroom, partnership, life.',true,true),
('li-archetype','emotional-support-shadow-daddy','Emotional Support Shadow Daddy','A dark, intimidating hero who is surprisingly caring, emotionally available, and devoted. The shadow daddy who also remembers her favorite tea.',true,true),
('li-archetype','golden-retriever','Golden Retriever','A loyal, warm, openly affectionate love interest — sunshine in human form.',true,true),
('li-archetype','grumpy-hero','Grumpy / Cold Hero','An emotionally reserved, distant hero. Softens only for her.',true,true),
('li-archetype','high-lord','High Lord','A powerful ruler of a magical territory or court, used to being obeyed and undone only by her.',true,true),
('li-archetype','highlander-hero','Highlander Hero','A hero from the Scottish Highlands or inspired setting — kilts, clans, oaths, brogue.',true,true),
('li-archetype','himbo','Himbo','A kind-hearted but not particularly intellectual hero. Sweet, devoted, frequently shirtless.',true,true),
('li-archetype','immortal-hero','Immortal Hero','A romantic lead who has lived for centuries or longer. Waited for her. Specifically.',true,true),
('li-archetype','immortal','Immortal Love Interest','A lover who has lived for centuries — and, conveniently, waited.',true,true),
('li-archetype','men-in-uniform','Men in Uniform','A hero serving in military, police, fire, or similar professions. Discipline, duty, off-duty trouble.',true,true),
('li-archetype','morally-grey','Morally Grey','A hero whose ethics bend — willing to do terrible things, usually for her.',true,true),
('li-archetype','morally-grey-mmc','Morally Grey MMC','A male main character whose actions blur the line between right and wrong — willing to break rules, ethics, kingdoms for her.',true,true),
('li-archetype','nerdy-hero','Nerdy Hero','A hero known for intelligence, academics, or niche obsessions. The quiet kind.',true,true),
('li-archetype','non-human-hero','Non-Human Hero','A hero who is not fully human.',true,true),
('li-archetype','pirate-hero','Pirate Hero','A seafaring outlaw or privateer.',true,true),
('li-archetype','politician-hero','Politician Hero','A hero involved in government or politics.',true,true),
('li-archetype','possessive-hero','Possessive Hero','A hero who is intensely protective and territorial. "Mine" is a position, not a guess.',true,true),
('li-archetype','rich-hero','Rich Hero','A wealthy or financially powerful hero.',true,true),
('li-archetype','rockstar','Rockstar','A musician or performer — fame, chaos, the song he wrote about her.',true,true),
('li-archetype','royal-hero','Royal Hero','A king, prince, duke, or noble hero. Crown, duty, one extremely inconvenient feeling.',true,true),
('li-archetype','sheik','Sheik','A hero of Middle Eastern royal or noble status.',true,true),
('li-archetype','shy-hero','Shy Hero','A reserved, awkward, or introverted hero. Pining loud on the inside.',true,true),
('li-archetype','single-father','Single Father','A hero raising children on his own. Stakes raised, heart larger.',true,true),
('li-archetype','stalker-hero','Stalker Hero','A hero who obsessively follows or monitors another character.',true,true),
('li-archetype','stern-brunch-daddy','Stern Brunch Daddy','Older, distinguished, authoritative-but-nurturing. The look that says "I''ll order for the table and fix all your problems."',true,true),
('li-archetype','sunny-hero','Sunny / Happy Hero','An optimistic, upbeat hero. The bright one in a brooding genre.',true,true),
('li-archetype','sweet-hero','Sweet / Gentle Hero','A compassionate, caring hero. Soft on her specifically.',true,true),
('li-archetype','teacher-hero','Teacher / Coach Hero','A hero working as an educator or coach.',true,true),
('li-archetype','tortured','Tortured','A love interest carrying trauma, guilt, or scars that make intimacy a battle worth winning.',true,true),
('li-archetype','viking-hero','Viking Hero','A Norse-inspired warrior or explorer hero — raids, oaths, devotion that lasts a saga.',true,true),
('li-archetype','warlord','Warlord','A military leader or battlefield commander — strategy, scars, the moment he chooses softness.',true,true),
('li-archetype','working-class-hero','Working-Class Hero','A hero from a labor or trade profession.',true,true),
('mc-archetype','40s','40s +','Female protagonist is forty or older. Can be 100 +',true,true),
('mc-archetype','alpha-female','Alpha Female','A dominant, confident female lead who commands authority and respect — the room turns when she enters.',true,true),
('mc-archetype','royal-heroine','Aristo / Royal Heroine','A heroine of noble or royal status.',true,true),
('mc-archetype','aristocrat-aristo','Aristocrat (Aristo)','Short for aristocrat: a noble or upper-class character whose status, title, or family shapes the story.',true,true),
('mc-archetype','asexual-heroine','Asexual Heroine','A heroine who experiences little or no sexual attraction. Romance built differently.',true,true),
('mc-archetype','athlete','Athlete','A professional or competitive athlete.',true,true),
('mc-archetype','athlete-heroine','Athlete Heroine','A heroine involved in competitive sports.',true,true),
('mc-archetype','bodyguard-heroine','Bodyguard / Protector Heroine','A heroine tasked with protecting others.',true,true),
('mc-archetype','cheerful-heroine','Cheerful / Sunshine Heroine','An optimistic, upbeat female protagonist. Sunshine to his grump.',true,true),
('mc-archetype','cinnamon-roll','Cinnamon Roll','A gentle, sweet, kind-hearted character who is impossible to dislike.',true,true),
('mc-archetype','competent-heroine','Competent Heroine','A highly capable protagonist who excels at what she does. Quiet expertise.',true,true),
('mc-archetype','criminal-heroine','Criminal Heroine','A heroine engaged in criminal activity.',true,true),
('mc-archetype','curvy-heroine','Curvy Heroine','A heroine with a fuller body type.',true,true),
('mc-archetype','dangerous-heroine','Dangerous Heroine','A heroine capable of significant violence or destruction. The threat is part of the appeal.',true,true),
('mc-archetype','demisexual-heroine','Demisexual Heroine','A heroine who experiences attraction primarily after emotional connection.',true,true),
('mc-archetype','dominant-fmc','Dominant FMC','A female main character who takes a leading or controlling role in the relationship.',true,true),
('mc-archetype','early-20s-fmc','Early 20s FMC','Female protagonist is in her early twenties.',true,true),
('mc-archetype','famous-heroine','Famous Heroine','A heroine with celebrity or public recognition.',true,true),
('mc-archetype','female-rake','Female Rake','A confident heroine known for charm, flirtation, or sexual experience — owning her appetite.',true,true),
('mc-archetype','fierce','Fierce','A heroine with serious magical, political, or physical power — the threat, not the damsel.',true,true),
('mc-archetype','fighter','Fighter','A boxer, MMA fighter, or combat athlete.',true,true),
('mc-archetype','gifted-heroine','Gifted / Super-Heroine','A heroine with extraordinary abilities or talents — magic, intelligence, combat.',true,true),
('mc-archetype','grumpy-heroine','Grumpy / Ice Queen','A reserved or emotionally guarded heroine. Walls up. Softens only for him.',true,true),
('mc-archetype','immortal-heroine','Immortal Heroine','A heroine with an exceptionally long lifespan — vampire, fae, goddess, ancient being.',true,true),
('mc-archetype','in-their-30s','In Their 30s','Female protagonist is in her thirties.',true,true),
('mc-archetype','independent-heroine','Independent Heroine','A protagonist who values self-reliance and autonomy. Doesn''t need saving — but might let him try.',true,true),
('mc-archetype','non-human-heroine','Non-Human Heroine','A heroine who is not fully human — fae, shifter, demon, alien, more.',true,true),
('mc-archetype','plain-heroine','Plain Heroine','A heroine not characterized by exceptional beauty.',true,true),
('mc-archetype','poor-heroine','Poor Heroine','A heroine from a lower economic background.',true,true),
('mc-archetype','possessive-main-character','Possessive Main Character','A main character who is intensely protective or territorial about their love interest.',true,true),
('mc-archetype','powerful-fmc','Powerful FMC','A female protagonist with significant magical, political, or physical power. Not the prize — the threat.',true,true),
('mc-archetype','reluctant-hero','Reluctant Hero','A protagonist who resists the destiny, power, or role thrust upon her.',true,true),
('mc-archetype','rich-heroine','Rich Heroine','A heroine from wealth or privilege.',true,true),
('mc-archetype','sassy-heroine','Sassy Heroine','A witty, outspoken heroine with a sharp tongue and zero filter.',true,true),
('mc-archetype','scholar','Scholar','A protagonist driven by knowledge, research, or academic obsession.',true,true),
('mc-archetype','single-mother','Single Mother','A heroine raising children on her own — added stakes, real life, full heart.',true,true),
('mc-archetype','sleuth-heroine','Sleuth Heroine','A heroine who investigates mysteries.',true,true),
('mc-archetype','stalker-heroine','Stalker Heroine','A heroine who obsessively follows or monitors another character.',true,true),
('mc-archetype','sweet-heroine','Sweet / Gentle Heroine','A kind, compassionate protagonist — pure heart, surprising spine.',true,true),
('mc-archetype','take-charge-heroine','Take-Charge Heroine','A heroine who naturally assumes leadership — in love, in war, at the breakfast table.',true,true),
('mc-archetype','tall-heroine','Tall Heroine','A heroine notably taller than average.',true,true),
('mc-archetype','teacher-heroine','Teacher / Coach Heroine','A heroine working as an educator or coach.',true,true),
('mc-archetype','teenage-fmc','Teenage FMC','Female protagonist is a teenager.',true,true),
('mc-archetype','tortured-heroine','Tortured Heroine','A heroine carrying significant trauma or emotional pain. Healing is part of the romance.',true,true),
('mc-archetype','virgin-heroine','Virgin Heroine','A heroine with little or no prior sexual experience. Often paired with a more experienced LI.',true,true),
('mc-archetype','warrior-heroine','Warrior Heroine','A heroine skilled in combat.',true,true),
('mc-archetype','white-collar-heroine','White-Collar Heroine','A heroine in a professional career.',true,true),
('mc-archetype','working-class-heroine','Working-Class Heroine','A heroine from a labor or service profession.',true,true),
('mechanics','behind-closed-doors','Behind Closed Doors','Intimate scenes occur off-page — the camera cuts away at the bedroom door.',true,true),
('mechanics','burn','Burn','A descriptor for how fast a romance develops sexually — distinct from "slow-burn" the trope. A book can be "fast-burn" (immediate heat) or "slow-burn" (delayed).',true,true),
('mechanics','closed-door','Closed Door','Romance where sex happens but isn''t shown — fade-to-black, morning-after framing, imagination filling the gap.',true,true),
('mechanics','d-s','D/s (Dominance / Submission)','A power-exchange dynamic — bedroom or 24/7 — where one partner takes control and one yields. Consensual is the only kind that counts.',true,true),
('mechanics','dynamic','Dynamic','Relationship power dynamics play a significant role in intimacy.',true,true),
('mechanics','explicit-and-plentiful','Explicit & Plentiful','Frequent, highly explicit intimate scenes. The spiciest tier.',true,true),
('mechanics','explicit-open-door','Explicit Open Door','Intimate scenes shown on the page with explicit detail.',true,true),
('mechanics','fade-to-black','Fade to Black','A scene that cuts away just before or during a sexual encounter — the close-door convention in action.',true,true),
('mechanics','glimpses-and-kisses','Glimpses & Kisses','Minimal on-page intimacy — hand-holding, embraces, the occasional kiss. Sweetest end of the spice scale.',true,true),
('mechanics','high-spice','High Spice','Romance with very explicit sexual content — typically 4–5 chilis on smutHub''s scale.',true,true),
('mechanics','open-door','Open Door','Romance where sex scenes are shown explicitly on the page.',true,true),
('mechanics','safe-word','Safe Word','An agreed-upon word that immediately stops a scene in kink contexts. Non-negotiable infrastructure for consent.',true,true),
('mechanics','smut','Smut','Affectionate shorthand for explicit sexual content in romance.',true,true),
('mechanics','spice','Spice (Heat Level)','A reader-shorthand rating for how explicit a book''s sexual content is, usually on a 0–5 chili-pepper scale.',true,true),
('mood','academia','Academia','A scholarly setting or atmosphere involving schools, libraries, research, intellectual rivalry, or campus life.',true,true),
('mood','action-packed','Action-Packed','Fast-paced storytelling with frequent fights, chases, danger, or major plot events.',true,true),
('mood','adventure','Adventure','A story built around journeys, discovery, danger, quests, or exploration.',true,true),
('mood','angels','Angels','Features angelic beings.',true,true),
('mood','angsty','Angsty','Emotional turmoil, longing, heartbreak, and internal conflict — the good pain.',true,true),
('mood','atmospheric','Atmospheric','A story whose setting, mood, and sensory detail create a strong, immersive feeling.',true,true),
('mood','book-club','Book Club','A book well suited to group reading and discussion, often because of its themes, twists, or strong opinions.',true,true),
('mood','cozy','Cozy','Warm, comforting storytelling with lower tension, inviting settings, and an emphasis on community or everyday pleasures.',true,true),
('mood','cruel','Cruel','A story featuring intentionally harsh or hurtful behavior, often from a morally dark character or love interest.',true,true),
('mood','dangerous','Dangerous','A high-risk story involving threatening characters, deadly situations, or relationships with real consequences.',true,true),
('mood','dark','Dark','A heavy or unsettling tone involving morally difficult themes, danger, trauma, or violence.',true,true),
('mood','dark-academia','Dark Academia','A moody academic aesthetic involving elite schools, secret societies, obsession, ambition, and often mystery or danger.',true,true),
('mood','dark-and-twisted','Dark and Twisted','A story featuring morally complex characters, darker themes, and intense conflict.',true,true),
('mood','dark-fantasy','Dark Fantasy','Fantasy with grim, frightening, violent, or morally bleak themes and worldbuilding.',true,true),
('mood','devastating','Devastating','A book engineered to wreck you emotionally.',true,true),
('mood','dragons','Dragons','A story featuring dragons as creatures, rulers, enemies, companions, or bonded partners.',true,true),
('mood','dreamy','Dreamy','Soft, romantic, or surreal storytelling with an enchanting, floaty atmosphere.',true,true),
('mood','emotional','Emotional','Designed to create strong feelings such as joy, grief, heartbreak, longing, or catharsis.',true,true),
('mood','fantasy-romance','Fantasy Romance','A fantasy story where the romance is central to the plot and emotional resolution.',true,true),
('mood','gods','Gods','A story in which gods or divine beings directly influence the characters, magic, or conflict.',true,true),
('mood','gritty','Gritty','Raw, harsh storytelling that emphasizes struggle, violence, flawed characters, or difficult realities.',true,true),
('mood','hopeful','Hopeful','A story that maintains optimism, healing, or the possibility of a better future despite conflict.',true,true),
('mood','intense','Intense','A high-emotion, high-stakes reading experience with strong tension or dramatic conflict.',true,true),
('mood','lighthearted','Lighthearted','A fun, easygoing tone with humor and relatively low emotional heaviness.',true,true),
('mood','marriage','Marriage','A story where an existing, planned, or unexpected marriage is central to the plot.',true,true),
('mood','melancholic','Melancholic','A wistful, sorrowful tone shaped by loss, longing, nostalgia, or quiet sadness.',true,true),
('mood','mermaids','Mermaids','A story featuring mermaids, sirens, or other aquatic people and their underwater or coastal worlds.',true,true),
('mood','pirates','Pirates','A story featuring pirates, privateers, ships, treasure, and seafaring adventure.',true,true),
('mood','playful','Playful','A flirtatious, humorous, or mischievous tone that keeps the story fun.',true,true),
('mood','shapeshifters','Shapeshifters','Characters who can transform between human and animal, monster, or other supernatural forms.',true,true),
('mood','steamy','Steamy','Contains strong sexual tension and on-page intimacy, generally at a higher heat level.',true,true),
('mood','summer','Summer','A story with a summery setting or seasonal feeling, often involving travel, beaches, vacation, or warm-weather romance.',true,true),
('mood','supernatural','Supernatural','Features beings, powers, or events that exist beyond ordinary natural explanation.',true,true),
('mood','sweet','Sweet','A gentle, affectionate romance with low explicit content and an emphasis on emotional connection.',true,true),
('mood','swoony','Swoony','Full of romantic moments designed to make the reader melt, sigh, or fall a little in love too.',true,true),
('mood','tense','Tense','Creates sustained suspense, uncertainty, conflict, or emotional pressure.',true,true),
('mood','vampires','Vampires','Features vampire characters.',true,true),
('mood','werewolves','Werewolves','Features werewolves or shifters.',true,true),
('mood','whimsical','Whimsical','Playful, imaginative storytelling with charming, unusual, or fairy-tale-like elements.',true,true),
('omegaverse','alpha','Alpha','In omegaverse: the designation that experiences ruts, knots, and often projects dominance. Personality varies — not all alphas are alphaholes.',true,true),
('omegaverse','heat','Heat','In omegaverse: a biological cycle where Omegas experience intense drive to mate. Usually requires an Alpha or suppressants to manage. Distinct from "heat level" (spice rating).',true,true),
('omegaverse','knotting','Knotting','A canine/wolf-derived mating mechanic in omegaverse and shifter romance where the Alpha "knots" during sex, physically bonding the pair.',true,true),
('omegaverse','mpreg','Mpreg','Male pregnancy — common in omegaverse where male Omegas can carry young. A whole subgenre with dedicated readers.',true,true),
('omegaverse','omega','Omega','In omegaverse: the designation that experiences heats, can be knotted, often bears young regardless of gender. Not inherently submissive — personality varies.',true,true),
('omegaverse','omegaverse','Omegaverse','A romance worldbuilding system featuring biological designations — Alphas (rut), Omegas (heat), Betas (neutral) — with knotting, scent-bonding, mate dynamics, and often mpreg. Distinct from basic shifter pack romance though they often overlap.',true,true),
('omegaverse','scent-marking','Scent Marking','In shifter and omegaverse romance: leaving your scent on a mate to claim them. Ranges from subtle (a press of the wrist) to primal.',true,true),
('omegaverse','shifting','Shifting','The transformation between human and animal forms. Painful or seamless depending on the world. Some can partial-shift (claws, eyes). Often tied to emotion, the moon, or choice.',true,true),
('omegaverse','suppressants','Suppressants','In omegaverse: medication that suppresses heats or ruts. Lets characters function "normally" but often has plot-relevant side effects or failures.',true,true),
('pov','dual-pov','Dual POV','A story alternates between two characters'' perspectives — usually the main love interests.',true,true),
('pov','first-person-pov','First-Person POV','Narrated as "I felt," "I knew" — placing the reader fully inside one character.',true,true),
('pov','pov','POV (Point of View)','The character whose perspective the reader experiences. Romantasy is largely written in 1st-person POV; multi-POV is common in epic romantasy.',true,true),
('pov','single-pov','Single POV','The story is told from one character''s perspective — usually the protagonist.',true,true),
('pov','third-person-pov','Third-Person POV','Narrated as "she did," "he knew" — a step outside the character with more flexibility to show multiple perspectives.',true,true),
('representation','african-american','African-American','A story featuring an African-American main character — culturally specific representation.',true,true),
('representation','amish','Amish','Features Amish characters, communities, or culture.',true,true),
('representation','bisexual','Bisexual','A main character is bisexual — attracted to more than one gender.',true,true),
('representation','black-mc','Black MC','A story featuring a Black main character — own-voices, representation, identity at the center.',true,true),
('representation','buddhist','Buddhist','Includes Buddhist beliefs, practices, or characters.',true,true),
('representation','bw-wm','BW/WM Romance','A romance between a Black woman and White man — a specific representation niche.',true,true),
('representation','christian','Christian Romance','Includes Christian beliefs, practices, or characters. Often a clean-romance subgenre with explicit values.',true,true),
('representation','disabilities-scars','Disabilities & Scars','Features characters with significant disabilities, visible scars, or disfigurement — desirable, not despite. Representation done right.',true,true),
('representation','east-asian-mc','East Asian MC','A story featuring an East Asian main character — Chinese, Japanese, Korean, and more.',true,true),
('representation','faith','Faith','Religious beliefs play a meaningful role in the story — practice, doubt, devotion.',true,true),
('representation','gay','Gay','A romance between two men — MM romance.',true,true),
('representation','hindu','Hindu','Includes Hindu beliefs, practices, or characters.',true,true),
('representation','indigenous-mc','Indigenous MC','A story featuring an Indigenous main character — own-voices representation matters here.',true,true),
('representation','jewish','Jewish Romance','Includes Jewish beliefs, practices, or characters.',true,true),
('representation','latinx-mc','Latinx MC','A story featuring a Latinx main character.',true,true),
('representation','lesbian','Lesbian','A romance between two women — FF / WLW romance.',true,true),
('representation','lgbtq','LGBTQ+','Stories featuring lesbian, gay, bisexual, transgender, queer, or other LGBTQ+ characters and relationships.',true,true),
('representation','muslim','Muslim Romance','Includes Muslim beliefs, practices, or characters.',true,true),
('representation','neurodivergent','Neurodivergent','A main character is neurodivergent — autistic, ADHD, etc. Often own-voices.',true,true),
('representation','non-binary','Non-Binary Romance','A romance featuring a non-binary lead.',true,true),
('representation','pagan','Pagan','Includes pagan religions, traditions, or practices.',true,true),
('representation','queer-awakening','Queer Awakening','A character discovers, names, or explores their queer identity through the story.',true,true),
('representation','queer-romance','Queer Romance','Features LGBTQ+ romantic relationships — umbrella term.',true,true),
('representation','south-asian-mc','South Asian / Desi MC','A story featuring a South Asian / Desi main character.',true,true),
('representation','southeast-asian-mc','Southeast Asian MC','A story featuring a Southeast Asian main character.',true,true),
('representation','wlw','WLW','women loving women',true,true),
('setting','academy','Academy','A school or training ground where romance brews between classes, trials, and rivalries.',true,true),
('setting','alien-planet','Alien Planet','Set on a planet inhabited by alien species — foreign culture, biology, customs.',true,true),
('setting','college','College','A story set in a college or university — exams, parties, professors who shouldn''t.',true,true),
('setting','dragon-academy','Dragon Academy','A school or training environment focused on dragons and their riders.',true,true),
('setting','dystopia','Dystopia','Set in an oppressive or damaged society, often involving authoritarian control, inequality, or rebellion.',true,true),
('setting','fae-court','Fae Court','A magical society ruled by fae nobility — all glamour, bargains, rivalry, and danger.',true,true),
('setting','high-school','High School','Set during high school years — coming-of-age, first loves, hallway politics.',true,true),
('setting','human-colony','Human Colony','Set within a human settlement on another world — frontier dynamics in space.',true,true),
('setting','small-town','Small Town','Set in a close-knit small community — everyone knows everyone, nothing stays secret.',true,true),
('setting','space','Space','Primarily set in outer space — vast distances, alien worlds, ship-bound romance.',true,true),
('setting','space-station','Space Station','Set aboard a space station — a hub of cultures, politics, secrets.',true,true),
('setting','spaceship','Spaceship','A spacecraft is the primary setting — tight quarters, forced proximity, deep space.',true,true),
('setting','workplace','Workplace / Office','Set in a professional environment — office romance, coworkers, after-hours.',true,true),
('sport','baseball','Baseball','A baseball romance — diamonds, seasons, slow burns paced like the game.',true,true),
('sport','basketball','Basketball','A basketball romance — courts, championships, after-game heat.',true,true),
('sport','mma','Fighting / MMA / Boxing','A fighting-sports romance — rings, cages, controlled violence and uncontrollable feelings.',true,true),
('sport','football','Football','A football romance — players, coaches, locker rooms, the field.',true,true),
('sport','hockey','Hockey','A hockey romance — rink, road games, the way they take care of each other.',true,true),
('sport','skating','Ice / Figure Skating','A skating romance — ice, partner work, lifts that mean something.',true,true),
('sport','soccer','Soccer / Football','A soccer / football romance — pitches, World Cups, devotion as a team sport.',true,true),
('sport','sports','Sports','A romance or story set around athletes, teams, training, or competition.',true,true),
('subgenre','aliens','Aliens','Features extraterrestrial characters.',true,true),
('subgenre','contemporary-romance','Contemporary Romance','Romance set in the present-day real world — no magic, no time travel, just modern people falling in love.',true,true),
('subgenre','dark-romance','Dark Romance','A romance subgenre that leans into morally compromised characters, dubious or non-consent dynamics, violence, and content that pushes past the comfort zone of mainstream romance.',true,true),
('subgenre','demon-romance','Demon Romance','A romance featuring a demon or demonic love interest.',true,true),
('subgenre','dystopian','Dystopian Romance','Romance set in a broken, oppressive, or post-collapse society.',true,true),
('subgenre','fantasy','Fantasy','A story featuring magical or supernatural elements as central to the world or plot.',true,true),
('subgenre','romantic-comedy','Funny / Romantic Comedy','Romance with humor as a primary tone — banter, hijinks, situational comedy.',true,true),
('subgenre','high-fantasy','High Fantasy','Fantasy set in a fully fictional secondary world with extensive worldbuilding, often featuring epic stakes and elaborate magic systems.',true,true),
('subgenre','historical-romance','Historical Romance','Romance set in the past — Regency, Victorian, medieval, or any historical period.',true,true),
('subgenre','horror-romance','Horror Romance','Romance with horror elements designed to unsettle as much as seduce.',true,true),
('subgenre','new-adult','New Adult','Focuses on characters transitioning into adulthood.',true,true),
('subgenre','orcs','Orcs','Features orc characters or cultures.',true,true),
('subgenre','paranormal','Paranormal','Features supernatural beings or phenomena.',true,true),
('subgenre','paranormal-romance','Paranormal Romance','Romance with supernatural elements — vampires, shifters, witches, fae, demons, ghosts.',true,true),
('subgenre','pirate-romance','Pirate Romance','A romance set among pirates, privateers, or seafaring adventurers.',true,true),
('subgenre','romance','Romance','A genre centered on the development of a romantic relationship and an emotionally satisfying ending.',true,true),
('subgenre','romantasy','Romantasy','A genre that blends fantasy and romance — magical worlds and significant worldbuilding with a central love story driving the plot.',true,true),
('subgenre','mystery','Romantic Mystery','Romance interwoven with a mystery the leads must solve together.',true,true),
('subgenre','suspense','Romantic Suspense','Romance built around tension, danger, and uncertainty driving the plot.',true,true),
('subgenre','science-fantasy','Science Fantasy','A blend of science-fiction and fantasy elements, such as advanced technology alongside magic.',true,true),
('subgenre','science-fiction','Science Fiction','Speculative fiction based on future technology, space, science, aliens, or altered societies.',true,true),
('subgenre','sports-romance','Sports Romance','Romance set within competitive sports — athletes, coaches, teams, championships.',true,true),
('subgenre','steampunk','Steampunk Romance','Romance combining fantasy or sci-fi with Victorian-era technology — gears, steam, airships, and corsets.',true,true),
('subgenre','urban-fantasy','Urban Fantasy','Fantasy set in a contemporary, usually urban setting — magic in the modern world.',true,true),
('subgenre','vampire-romance','Vampire Romance','A romance with a vampire love interest — bite, bond, eternal devotion.',true,true),
('subgenre','western','Western','Set in the American West or a western-inspired world, often featuring ranches, frontier towns, or cowboys.',true,true),
('subgenre','witch-romance','Witch Romance','A romance centered on a witch or magical practitioner.',true,true),
('subgenre','young-adult','Young Adult','Written primarily for teen readers.',true,true),
('time-period','twentieth-century','20th Century','Set during the 1900s — Roaring Twenties, World Wars, mid-century, late 1900s.',true,true),
('time-period','american-civil-war','American Civil War','Set during or around the American Civil War (1861–1865).',true,true),
('time-period','ancient','Ancient Times','Settings inspired by ancient civilizations — Egypt, Rome, Greece, Mesopotamia.',true,true),
('time-period','contemporary','Contemporary','Set in the present day — no magic, no time travel, just modern romance.',true,true),
('time-period','futuristic','Futuristic','Set in a future — near-future, sci-fi, post-apocalyptic, or speculative.',true,true),
('time-period','georgian','Georgian','Set during the Georgian era (1714–1830) — elegance, scandal, the rise of the rake.',true,true),
('time-period','medieval','Medieval','Set during a medieval-inspired era — castles, knights, courts, sword and crown.',true,true),
('time-period','tudor-stuart','Tudor & Stuart','Set during the Tudor or Stuart periods of England (1485–1714).',true,true),
('time-period','victorian','Victorian','Set during the Victorian era (1837–1901) — moral codes, repression, secret desires.',true,true),
('time-period','western-frontier','Western Frontier','Set during frontier expansion — cowboys, ranches, lawless towns.',true,true),
('trope','abduction','Abduction','A character is taken — often by the love interest, sometimes by an antagonist.',true,true),
('trope','academy-romance','Academy Romance','Romance developing within a school, academy, or training environment.',true,true),
('trope','age-gap','Age Gap','A significant age difference between the romantic leads — experience meets youth, or vice versa.',true,true),
('trope','angel','Angel','A story featuring an angelic or celestial character, often with divine powers, rules, or forbidden desires.',true,true),
('trope','arranged-forced-marriage','Arranged Forced Marriage','Characters are required or pressured to marry by family, politics, law, or circumstance rather than personal choice.',true,true),
('trope','arranged-marriage','Arranged Marriage','Characters married off by family, court, or contract — love arrives second.',true,true),
('trope','assassin','Assassin','A story featuring a trained killer, often caught between a dangerous mission and an inconvenient attraction.',true,true),
('trope','bear-shifter','Bear Shifter','Characters can shift into bears.',true,true),
('trope','best-friends-brother','Best Friend''s Brother','A romance with your best friend''s sibling — forbidden, awkward, irresistible.',true,true),
('trope','best-friends-parent','Best Friend''s Parent','Romance with a best friend''s parent. Forbidden, complicated, the kind of trope readers know exactly why they''re here for.',true,true),
('trope','betrayal','Betrayal','A major breach of trust drives the story — secrets revealed, sides switched, love tested.',true,true),
('trope','billionaire-romance','Billionaire Romance','A romance featuring an extremely wealthy and powerful love interest.',true,true),
('trope','blood-bond','Blood Bond','A supernatural connection created or sealed through blood, often linking characters’ magic, emotions, or lives.',true,true),
('trope','bodyguard','Bodyguard','One character is assigned to protect another, creating danger, forced proximity, and usually very unprofessional feelings.',true,true),
('trope','bonded-pair','Bonded Pair','Characters connected through a supernatural or magical bond.',true,true),
('trope','boss-employee','Boss / Employee','A romance between a superior and subordinate — workplace ethics, complicated power, very motivated readers.',true,true),
('trope','broken-bond','Broken Bond','A magical or emotional connection that has been damaged or severed.',true,true),
('trope','brothers-best-friend','Brother''s Best Friend','A romance between a character and their brother’s best friend, often complicated by loyalty, secrecy, or protective siblings.',true,true),
('trope','bully-romance','Bully Romance','A romance where one lead initially intimidates, humiliates, or mistreats the other; content warnings are especially important.',true,true),
('trope','burn-the-world-for-her','Burn the World for Her','a character would sacrifice everything, including morality, for their partner',true,true),
('trope','captive','Captive','A story in which a character is held prisoner or prevented from leaving.',true,true),
('trope','captive-romance','Captive Romance','A dark-romance setup involving a captor and captive; consent and power imbalance are central concerns, so check warnings.',true,true),
('trope','caretaking','Caretaking','One character actively looks after another — illness, injury, emotional crisis — and the line between caretaker and lover blurs.',true,true),
('trope','cheating','Cheating','Infidelity occurs within a romantic relationship — sometimes the inciting incident, sometimes the wound.',true,true),
('trope','chosen-family','Chosen Family','Similar to found family, emphasizing intentionally formed emotional connections.',true,true),
('trope','chosen-one','Chosen One','A character marked by prophecy, magic, or fate for an important role.',true,true),
('trope','class-difference','Class Difference','Significant economic or social class differences exist.',true,true),
('trope','court','Court','A royal or fae social setting shaped by rulers, nobles, alliances, etiquette, and political maneuvering.',true,true),
('trope','court-intrigue','Court Intrigue','Political scheming, shifting alliances, and betrayals inside a royal or fae court.',true,true),
('trope','court-politics','Court Politics','Political maneuvering, alliances, betrayals, and power struggles among nobility.',true,true),
('trope','deadly-trials','Deadly Trials','Characters must survive lethal tests, competitions, or challenges.',true,true),
('trope','demon','Demon','A story featuring a demonic or infernal character, often dangerous, powerful, and unexpectedly romantic.',true,true),
('trope','dragon-rider','Dragon Rider','A trope where the male love interest is a dragon rider — usually in an academy or military setting, with a soul-bonded dragon and a high-stakes magical war as the backdrop.',true,true),
('trope','dragon-shifter','Dragon Shifter','Characters can shift into dragons.',true,true),
('trope','enemies-to-lovers','Enemies to Lovers','A romance in which the love interests start as antagonists — rivals, opposing sides, mutual loathing — and gradually convert that animosity into desire.',true,true),
('trope','enemies-with-benefits','Enemies with Benefits','Characters who dislike or oppose each other begin a sexual relationship before resolving their emotional conflict.',true,true),
('trope','enemy-kingdoms','Enemy Kingdoms','The leads belong to warring nations, courts, or factions.',true,true),
('trope','fae','Fae','Magical beings associated with fairy lore — tall, often pointed-eared, otherworldly in beauty, frequently organized into magical courts with their own powers and politics.',true,true),
('trope','fake-dating','Fake Dating','Characters pretend to be a couple — for a wedding, a contract, family pressure — and discover the pretense is concealing real feelings.',true,true),
('trope','fake-engagement','Fake Engagement','Characters pretend to be engaged for personal, social, or strategic reasons — until pretend gets too real.',true,true),
('trope','fallen-angel','Fallen Angel','An angelic being cast out from heaven or stripped of divine status — a different kind of grace.',true,true),
('trope','fate-bound','Fate Bound','Characters are connected through destiny, prophecy, or supernatural forces.',true,true),
('trope','fated-mates','Fated Mates','A trope where two characters are magically, spiritually, or cosmically destined to be together — often with consequences for rejecting the bond.',true,true),
('trope','fish-out-of-water','Fish Out of Water','A character dropped into an unfamiliar world, court, or culture, learning the rules in real time.',true,true),
('trope','forced-bond','Forced Bond','Characters linked together against their will through magic or circumstance.',true,true),
('trope','forced-proximity','Forced Proximity','A trope where characters who would otherwise stay apart are required by circumstance to be together — sharing a cabin, road trip, safehouse, or single room.',true,true),
('trope','found-family','Found Family','Characters form deep family-like bonds outside of blood — chosen, fought for, protected.',true,true),
('trope','friends-to-lovers','Friends to Lovers','A romance that starts in established friendship and transitions into something more.',true,true),
('trope','friends-with-benefits','Friends with Benefits','Sex without commitment between people who like each other — until one of them stops being able to keep it casual.',true,true),
('trope','good-grovel','Good Grovel','A character who caused harm or betrayal makes a meaningful, satisfying effort to earn forgiveness — not a quick "sorry."',true,true),
('trope','grumpy','Grumpy','An irritable, guarded, or emotionally reserved character—often secretly soft for exactly one person.',true,true),
('trope','grumpy-sunshine','Grumpy x Sunshine','A pairing of one perpetually scowling character and one relentlessly warm one — the grump goes soft only for the sunshine.',true,true),
('trope','he-falls-first','He Falls First','A pacing trope where the male love interest realizes his feelings well before the heroine does.',true,true),
('trope','he-fell-first','He Fell First','he caught feelings before she did. Pairs well with wine and a “she fell harder” for max impact',true,true),
('trope','height-difference','Height Difference','Noticeable height difference between leads.',true,true),
('trope','heist','Heist','A plot centered on planning and executing a theft, usually with a skilled crew, high stakes, and betrayals.',true,true),
('trope','hidden-identity','Hidden Identity','A character conceals their name, status, species, powers, or true allegiance from others.',true,true),
('trope','historical','Historical','Set in a past historical period.',true,true),
('trope','hurt-comfort','Hurt / Comfort','One character experiences pain — physical or emotional — and another provides care and presence.',true,true),
('trope','insta-love','Insta Love','Characters develop romantic feelings almost immediately after meeting.',true,true),
('trope','jealousy','Jealousy','Romantic tension driven by fear of losing someone’s affection or by attention from a perceived rival.',true,true),
('trope','just-one-bed','Just One Bed','also ‘only one bed’ situation where sharing a bed is necessary by all means. (insert wink face)',true,true),
('trope','kidnapping','Kidnapping','A character is abducted or held against their will; check content warnings for how the story handles captivity and consent.',true,true),
('trope','lion-shifter','Lion Shifter','Characters can shift into lions.',true,true),
('trope','lost-heir','Lost Heir','A missing or hidden heir discovers their true identity and claim.',true,true),
('trope','love-triangle','Love Triangle','Romantic conflict involving three people — and only one can win.',true,true),
('trope','lovers-to-enemies','Lovers to Enemies','Former lovers become opponents through betrayal, conflict, politics, or divided loyalties.',true,true),
('trope','mafia-romance','Mafia Romance','Romance set in organized crime — loyalty, danger, blood oaths, complicated love.',true,true),
('trope','magic','Magic','Magical systems play a major role.',true,true),
('trope','magic-school','Magic School','An academy where characters learn to use magic, often featuring training, rivalries, exams, and dangerous secrets.',true,true),
('trope','marriage-first','Marriage First','The characters marry before falling in love, so the relationship develops after the vows.',true,true),
('trope','marriage-in-trouble','Marriage in Trouble','An established couple faces conflict, separation, or lost intimacy and must decide whether to rebuild their relationship.',true,true),
('trope','marriage-of-convenience','Marriage of Convenience','Characters marry for strategy, safety, or politics — and fall in love after the paperwork.',true,true),
('trope','masquerade','Masquerade','A masked ball or concealed-identity event where attraction, mistaken identity, and secrets take center stage.',true,true),
('trope','mate','Mate','a romantic commitment similar to marriage',true,true),
('trope','mated-pair','Mated Pair','Characters recognized as destined romantic partners through supernatural means.',true,true),
('trope','mentor','Mentor','A more experienced character trains or guides another; the relationship may remain platonic or develop romantic tension.',true,true),
('trope','military-academy','Military Academy','A story set at a school that trains soldiers, warriors, riders, or commanders under strict and dangerous conditions.',true,true),
('trope','military-romance','Military Romance','Romance involving active military service or veterans — duty, deployment, coming home.',true,true),
('trope','monster-romance','Monster Romance','A romance with a non-human or monstrous love interest.',true,true),
('trope','monsters','Monsters','Stories featuring non-human creatures as central characters, threats, or romantic interests.',true,true),
('trope','motorcycle-club','Motorcycle Club','A romance centered on an organized motorcycle club, often involving loyalty, danger, found family, and club rules.',true,true),
('trope','multicultural','Multicultural Romance','A romance involving characters from different cultural backgrounds — bridging, blending, sometimes clashing.',true,true),
('trope','mutual-pining','Mutual Pining','Both characters are in love with each other but neither has said it — sometimes neither has admitted it to themselves.',true,true),
('trope','mythology','Mythology','A story drawing on gods, legends, heroes, creatures, or belief systems from cultural mythologies.',true,true),
('trope','necromancer','Necromancer','A magic user who communicates with, controls, or raises the dead.',true,true),
('trope','one-horse','One Horse','characters are forced to share a single horse or mode of transportation, creating proximity',true,true),
('trope','one-night-stand','One Night Stand','A sexual encounter intended to happen once—until circumstances, feelings, or fate bring the characters together again.',true,true),
('trope','only-one-bed','Only One Bed','A setup where the characters must share a single sleeping space — by reservation error, snowstorm, hideout, or contrived circumstance.',true,true),
('trope','opposites-attract','Opposites Attract','Characters with contrasting personalities, lifestyles, or values discover they fit together better than expected.',true,true),
('trope','parents-best-friend','Parent''s Best Friend','Romance with a parent''s close friend — they''ve known you since you were small. Now they''re seeing you differently.',true,true),
('trope','pining','Pining','Longing for someone from a distance, often without knowing whether the feelings are returned.',true,true),
('trope','pirate','Pirate','A story featuring pirates, privateers, sea voyages, treasure, danger, and romance beyond the law.',true,true),
('trope','political','Political','A story where governance, alliances, succession, rebellion, or diplomacy significantly drives the plot.',true,true),
('trope','political-court-intrigue','Political Court Intrigue','Power struggles, schemes, and politics drive the plot.',true,true),
('trope','political-marriage','Political Marriage','a marriage arranged primarily for power, alliances, or strategic gain',true,true),
('trope','pregnancy','Pregnancy','A pregnancy plays a central role in the plot or relationship.',true,true),
('trope','quest-romance','Quest Romance','A romance that ignites on a dangerous journey or mission.',true,true),
('trope','redemption-arc','Redemption Arc','A character works to atone for past wrongs and become someone better.',true,true),
('trope','regency','Regency','Set during the Regency era (1811–1820) — Bridgerton territory. Balls, scandal, marriage of convenience.',true,true),
('trope','rejected-fated-mate','Rejected Fated Mate','One character refuses a destined romantic bond.',true,true),
('trope','rejected-mate','Rejected Mate','A fated bond that one partner refuses, at least at first — the rejection itself becomes the wound the story heals.',true,true),
('trope','rekindled-romance','Rekindled Romance','Former partners who find their way back to each other after time apart.',true,true),
('trope','revenge','Revenge','A story driven by a character''s pursuit of vengeance.',true,true),
('trope','reverse-harem-why-choose','Reverse Harem / Why Choose','A romance where one central character has multiple love interests and does not have to choose just one; also called why choose.',true,true),
('trope','reverse-love-triangle','Reverse Love Triangle','Multiple characters pursue the same romantic interest — the protagonist as the prize.',true,true),
('trope','rivals-to-lovers','Rivals to Lovers','Characters competing for the same goal gradually turn rivalry and tension into attraction.',true,true),
('trope','road-trip','Road Trip','Romance that develops while characters travel together.',true,true),
('trope','royal-heroine','Royal Heroine','A heroine who is a queen, princess, empress, or other noblewoman whose rank shapes the story.',true,true),
('trope','royal-romance','Royal Romance','Love among kings, queens, princes, and the thrones that complicate them.',true,true),
('trope','royalty','Royalty','A story centered on kings, queens, princes, princesses, succession, court life, or royal duty.',true,true),
('trope','second-chance','Second Chance','Former romantic partners reconnect and attempt to rebuild their relationship.',true,true),
('trope','secret-baby','Secret Baby','A character discovers they have a child they were previously unaware of.',true,true),
('trope','secret-relationship','Secret Relationship','Characters hide their romantic involvement from others — family, court, public.',true,true),
('trope','secret-royalty','Secret Royalty','A character who unknowingly holds a claim to a throne, title, or power.',true,true),
('trope','shadow-daddy','Shadow Daddy','A hero archetype: intimidating, dark, often morally grey, with shadow- or void-based magical abilities; possessive and devoted to his love interest.',true,true),
('trope','she-falls-first','She Falls First','The heroine develops romantic feelings before the other lead does.',true,true),
('trope','she-fell-harder','She Fell Harder','A companion pacing trope: when "he fell first" lands, her eventual feelings arrive with more force.',true,true),
('trope','shifter-romance','Shifter Romance','Paranormal romance featuring characters who shift between human and animal forms. Werewolves/wolves most common, but also bears, big cats, dragons, and basically any animal you can imagine. Often includes pack dynamics, mate bonds, and territorial behavior. May or may not include Omegaverse elements—check the blurb.',true,true),
('trope','short-stories','Short Stories','Brief standalone works, often collected together, that tell complete stories in fewer pages than a novel.',true,true),
('trope','siblings-best-friend','Sibling''s Best Friend','A romance with your sibling''s close friend — knew them forever, never like this.',true,true),
('trope','single-parent','Single Parent','A romance where one central character is raising a child or children on their own.',true,true),
('trope','slow-burn','Slow Burn','A romance where attraction builds over a long stretch of the book — sometimes the whole book — with delayed physical resolution.',true,true),
('trope','slow-burn-romance','Slow Burn Romance','Attraction develops gradually over a long period before romantic payoff occurs.',true,true),
('trope','slow-corruption','Slow Corruption','A character is gradually tempted, morally changed, or drawn toward darkness over the course of the story.',true,true),
('trope','snowed-in','Snowed In','Characters trapped together by weather — forced proximity with a fireplace.',true,true),
('trope','soul-bond','Soul Bond','A character who is biologically or magically destined to be the partner of another — without the lifelong commitment implication of "mate."',true,true),
('trope','soulmates','Soulmates','Two characters magically or spiritually bonded — sometimes telepathically, sometimes through ritual, sometimes by birth.',true,true),
('trope','spicy','Spicy','Contains frequent or explicit on-page sexual content.',true,true),
('trope','stalker','Stalker','A character obsessively follows or monitors another; commonly associated with dark romance and strong content warnings.',true,true),
('trope','step-siblings','Step-Siblings','A romance between characters who become siblings through marriage — not blood.',true,true),
('trope','superheroes','Superhero Romance','Romance featuring characters with superpowers or hidden identities.',true,true),
('trope','survival','Survival','Characters must endure dangerous conditions to survive — isolation forges intimacy.',true,true),
('trope','telepathic-bond','Telepathic Bond','A magical connection that allows characters to hear thoughts, share emotions, or communicate mind-to-mind.',true,true),
('trope','tiger-shifter','Tiger Shifter','Characters can shift into tigers.',true,true),
('trope','time-travel','Time Travel','Characters travel through time.',true,true),
('trope','time-travel-romance','Time-Travel Romance','Lovers separated or united across different eras.',true,true),
('trope','touch-her-and-die','Touch Her and Die','A possessive hero archetype where the love interest''s extreme protectiveness becomes a threat to anyone who looks sideways at the heroine.',true,true),
('trope','touch-starved','Touch Starved','A character has gone without affection or physical comfort and reacts strongly when safe touch is finally offered.',true,true),
('trope','tournament','Tournament','Competitors face each other in a structured magical or martial contest.',true,true),
('trope','training-arc','Training Arc','A stretch where the protagonist is forged through structured training and earns their power.',true,true),
('trope','true-mate','True Mate','A shifter/paranormal variation of fated mates — the destined partner, often recognized by scent or the shifter''s animal side, sometimes distinguished from a "chosen mate" picked by logic rather than fate.',true,true),
('trope','unrequited-love','Unrequited Love','One character carries romantic feelings the other doesn''t return — at least not yet.',true,true),
('trope','vampire','Vampire','A story featuring a vampire character, often involving immortality, blood, danger, and supernatural desire.',true,true),
('trope','vengeance','Vengeance','Revenge is a major motivation.',true,true),
('trope','villain-romance','Villain Romance','A romance where the love interest is the story''s antagonist — or close to it.',true,true),
('trope','virgin-hero','Virgin Hero','A male love interest who hasn''t had sex before the events of the book.',true,true),
('trope','virgin-hero-heroine','Virgin Hero/Heroine','A male/female lead with little or no prior sexual experience.',true,true),
('trope','war','War','War or active military conflict drives part of the story.',true,true),
('trope','war-time-romance','Wartime Romance','Love that takes root during active conflict.',true,true),
('trope','witch','Witch','A story featuring a witch or magical practitioner whose powers, coven, or craft shape the plot.',true,true),
('trope','witches','Witches','Features witches or magical practitioners.',true,true),
('trope','workplace-romance','Workplace Romance','A romance between colleagues or people connected through work, often complicated by professional boundaries.',true,true),
('vibe','epic','Epic','books 600 +',true,true),
('vibe','gothic','Gothic','Morally complex characters, darker themes, and sharp, unsettling conflict.',true,true),
('warning','ableism','Ableism','Depictions of discrimination, prejudice, or harmful attitudes toward disabled individuals.',true,true),
('warning','abuse','Abuse','Physical, emotional, psychological, verbal, or sexual abuse depicted within the story.',true,true),
('warning','abuse-between-mcs','Abuse Between Mcs','Abuse occurs between the main romantic characters. A serious flag many readers want to know about going in.',true,true),
('warning','alcoholism','Alcoholism','Alcohol dependency or addiction is depicted.',true,true),
('warning','animal-abuse','Animal Abuse','Animals are intentionally harmed, neglected, or mistreated on-page.',true,true),
('warning','animal-death','Animal Death','The death of an animal is depicted or discussed.',true,true),
('warning','birth-control-non-consent','Birth Control Non-Consent','One character interferes with, removes, or deceives another regarding birth control.',true,true),
('warning','body-betrayal','Body Betrayal','A character experiences unwanted physical attraction toward someone they dislike or distrust.',true,true),
('warning','child-death','Child Death','The death of a child is depicted or discussed.',true,true),
('warning','death-grief','Death Grief','Significant death, mourning, or bereavement is central to the story.',true,true),
('warning','drug-abuse','Drug Abuse','Misuse or addiction involving drugs is depicted.',true,true),
('warning','dubious-consent','Dubious Consent','Sexual situations where consent is unclear, impaired, pressured, or ethically questionable.',true,true),
('warning','eating-disorders','Eating Disorders','Depictions of disordered eating behaviors or eating disorder recovery.',true,true),
('warning','fatphobia','Fatphobia','Depictions of anti-fat bias, discrimination, or body shaming.',true,true),
('warning','forced-pregnancy','Forced Pregnancy','Pregnancy occurs through coercion, manipulation, magical compulsion, or lack of consent.',true,true),
('warning','gambling','Gambling','Problematic or significant gambling behavior is present.',true,true),
('warning','graphic-violence','Graphic Violence','Violence depicted in explicit detail — gore, torture, brutal combat.',true,true),
('warning','human-trafficking','Human Trafficking','Characters experience or are involved in forced exploitation or trafficking.',true,true),
('warning','incest','Incest','Sexual or romantic relationships between close family members.',true,true),
('warning','infertility','Infertility','Difficulty conceiving or carrying a pregnancy plays a role in the story.',true,true),
('warning','mental-illness','Mental Illness','Characters experience diagnosed or implied mental health conditions — depression, anxiety, psychosis, etc.',true,true),
('warning','mental-trauma','Mental Trauma','Characters experience significant psychological trauma — flashbacks, PTSD, dissociation.',true,true),
('warning','miscarriage','Miscarriage','Pregnancy loss is depicted or discussed.',true,true),
('warning','misogyny','Misogyny','Sexism, discrimination, or prejudice against women appears in the story.',true,true),
('warning','no-hea','No HEA','The story does not conclude with a Happily Ever After.',true,true),
('warning','non-consent-between-mcs','Non-Consent Between MCs','Sexual activity occurs between main characters without consent.',true,true),
('warning','non-traditional-hea','Non-Traditional HEA','The story ends positively but the ending differs from a conventional romantic resolution.',true,true),
('warning','past-abuse','Past Abuse','A character has a history of abuse predating the events of the story.',true,true),
('warning','past-child-abuse','Past Child Abuse','References to abuse experienced during childhood — character backstory.',true,true),
('warning','past-child-neglect','Past Child Neglect','References to neglect experienced during childhood — backstory or memory.',true,true),
('warning','past-child-sexual-abuse','Past Child Sexual Abuse','A child has a history of sexual abuse before the story begins.',true,true),
('warning','past-sexual-abuse','Past Sexual Abuse','A character has a history of sexual abuse before the story begins.',true,true),
('warning','queerphobia','Queerphobia','Homophobia, transphobia, or discrimination against LGBTQ+ individuals appears in the story.',true,true),
('warning','racism','Racism','Racial prejudice, discrimination, or racial violence appears in the story.',true,true),
('warning','rape','Rape','Sexual assault or rape is depicted or discussed. Always flag — readers deserve advance notice.',true,true),
('warning','religious-trauma','Religious Trauma','Psychological harm resulting from religious beliefs, institutions, or experiences.',true,true),
('warning','self-harm','Self-Harm','Intentional self-injury is depicted or discussed.',true,true),
('warning','slavery','Slavery','Slavery exists or plays a major role in the story.',true,true),
('warning','slut-shaming','Slut Shaming','Characters are criticized, judged, or humiliated for sexual behavior.',true,true),
('warning','stalking','Stalking','Persistent unwanted surveillance, following, or monitoring of a character.',true,true),
('warning','substance-abuse','Substance Abuse','Problematic use of drugs, alcohol, or other substances.',true,true),
('warning','suicide','Suicide','Suicide attempts, suicide, or suicidal ideation are depicted or discussed.',true,true),
('warning','terminal-illness','Terminal Illness','A character suffers from a life-limiting or incurable illness.',true,true),
('warning','third-party-abuse','Third Party Abuse','Abuse committed by a character outside the primary romantic relationship.',true,true),
('warning','third-party-sexual-abuse','Third-Party Sexual Abuse','Sexual assault committed by someone outside the primary relationship.',true,true),
('warning','torture-of-mcs','Torture Of Mcs','A main character experiences torture.',true,true),
('warning','torture-of-side-characters','Torture Of Side Characters','A secondary character experiences torture.',true,true),
('warning','trigger-warnings','Trigger Warnings','alerts about potentially triggering content. usually at the front of the book or in the blurb. Use these!',true,true),
('warning','victim-blaming','Victim Blaming','Responsibility for abuse, assault, or harm is placed on the victim rather than the perpetrator.',true,true),
('worldbuilding','affinity','Affinity','The specific type of magic a character can wield — elemental, mind-based, or esoteric.',true,true),
('worldbuilding','blood-magic','Blood Magic','Magic that requires blood as a source — costly, intimate, often forbidden.',true,true),
('worldbuilding','blood-oath','Blood Oath','A promise sealed in blood and enforced by magic.',true,true),
('worldbuilding','cursed-objects','Cursed Objects','Magical items carrying dangerous effects — heirlooms, weapons, jewelry with a price.',true,true),
('worldbuilding','dark-magic','Dark Magic','Magic tied to death, corruption, sacrifice, or forbidden power.',true,true),
('worldbuilding','demons','Demons','Features demonic beings.',true,true),
('worldbuilding','dragon-bond','Dragon Bond','The magical, telepathic tether between a rider and their dragon.',true,true),
('worldbuilding','dragon-riders','Dragon Riders','Humans bonded to dragons — telepathic link, war partner, soul match.',true,true),
('worldbuilding','dungeon-and-quests','Dungeon & Quests','Exploration and adventure are central elements.',true,true),
('worldbuilding','elemental-magic','Elemental Magic','Magic powered by control of natural elements — fire, water, earth, air.',true,true),
('worldbuilding','fate-bound-souls','Fate-Bound Souls','Destiny links characters together.',true,true),
('worldbuilding','gods-goddesses','Gods & Goddesses','Divine beings directly influence events — favored mortals, divine bargains, prophecy.',true,true),
('worldbuilding','kingdoms-empires','Kingdoms & Empires','Large political powers drive the story — alliances, wars, succession.',true,true),
('worldbuilding','affinity-magic','Magic System','The structured set of rules governing how magic works in a world — sources, limits, costs.',true,true),
('worldbuilding','magical-academy','Magical Academy','A school dedicated to teaching magic — Fourth Wing, ACOTAR''s Night Court training, Hogwarts-adjacent.',true,true),
('worldbuilding','magical-creatures','Magical Creatures','Supernatural beings populate the world — dragons, griffins, fae beasts.',true,true),
('worldbuilding','mate-bond','Mate Bond','The supernatural tie that marks two people as partners — by scent, fate, or magic.',true,true),
('worldbuilding','monster-hunting','Monster Hunting','Characters regularly fight dangerous creatures.',true,true),
('worldbuilding','necromancy','Necromancy','Magic of death, spirits, and resurrection — taboo in most worlds, devastating where allowed.',true,true),
('worldbuilding','parallel-worlds','Parallel Worlds','Multiple realities or dimensions exist — what-ifs given form.',true,true),
('worldbuilding','portal-key','Portal Key','A magic-infused key that transports the bearer to a chosen place — often single-use, often pricey.',true,true),
('worldbuilding','portals','Portals','Characters travel between worlds or realms via doorways, mirrors, or magical thresholds.',true,true),
('worldbuilding','prophecy','Prophecy','Future events are foretold and shape the plot — the chosen one, the inevitable, the loophole.',true,true),
('worldbuilding','reincarnation','Reincarnation','Characters reborn across lifetimes — lovers finding each other again and again.',true,true),
('worldbuilding','royal-courts','Royal Courts','Political systems ruled by nobility — succession, alliances, scheming nobles.',true,true),
('worldbuilding','royal-politics','Royal Politics','conflicts involving rulers, succession, alliances, and governance',true,true),
('worldbuilding','scry','Scry','Divination using crystals, water, blood, or tokens to find people or learn secrets.',true,true),
('worldbuilding','worldbuilding','Worldbuilding','The creation of a story’s setting, cultures, history, politics, magic, geography, and rules.',true,true)
on conflict (category, slug) do update set
  label            = excluded.label,
  description      = excluded.description,
  has_page         = true,
  glossary_visible = true;

do $$
declare
  described_count integer;
  page_count integer;
begin
  select count(*) into described_count
  from tags
  where glossary_visible = true and description is not null;

  select count(*) into page_count
  from tags
  where glossary_visible = true
    and description is not null
    and has_page is distinct from false;

  raise notice 'Glossary sync complete: % described terms, % page-eligible terms',
    described_count, page_count;
end $$;
